
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
import numpy as np
import datetime
import pandas as pd

from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.units import inch

def create_static_map_image(analyzer_df, show_arrows=True, width_inches=8, height_inches=6):
    """
    Create a stylized PNG map image using matplotlib without axes or grid
    Args:
        analyzer_df: DataFrame from GPXAnalyzer with route data
        show_arrows: Boolean to show directional arrows or simple markers (currently uses circles)
        width_inches: Width of the image in inches
        height_inches: Height of the image in inches
    Returns:
        BytesIO: PNG image data as bytes
    """
    fig, ax = plt.subplots(figsize=(width_inches, height_inches), dpi=150, facecolor='white')
    lats = analyzer_df['latitude'].values
    lons = analyzer_df['longitude'].values
    points = np.array([lons, lats]).T.reshape(-1, 1, 2)
    segments = np.concatenate([points[:-1], points[1:]], axis=1)
    n_segments = len(segments)
    colors_gradient = plt.cm.viridis(np.linspace(0, 1, n_segments))
    lc = LineCollection(segments, colors=colors_gradient, linewidths=4, alpha=0.8)
    line = ax.add_collection(lc)
    ax.scatter(lons[0], lats[0], c='#2ECC71', s=200, marker='o', 
              zorder=6, edgecolor='white', linewidth=3, alpha=0.9)
    if len(lons) > 1 and (lons[0] != lons[-1] or lats[0] != lats[-1]):
        ax.scatter(lons[-1], lats[-1], c='#E74C3C', s=200, marker='s', 
                  zorder=6, edgecolor='white', linewidth=3, alpha=0.9)
    ax.set_aspect('equal')
    lat_range = max(lats) - min(lats)
    lon_range = max(lons) - min(lons)
    padding = max(lat_range, lon_range) * 0.05
    ax.set_xlim(min(lons) - padding, max(lons) + padding)
    ax.set_ylim(min(lats) - padding, max(lats) + padding)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.set_facecolor('white')
    plt.subplots_adjust(left=0, right=1, top=1, bottom=0)
    img_buffer = BytesIO()
    plt.savefig(img_buffer, format='png', dpi=120, bbox_inches='tight', facecolor='white')
    img_buffer.seek(0)
    plt.close(fig)
    return img_buffer

def generate_gpx_analysis_pdf(analyzer, km_data, total_distance, pace_minutes, pace_seconds, finish_time, 
                             total_elevation_gain, use_metric=True, route_name="GPX Route", create_static_map_image=None, convert_to_miles=None, convert_to_mph=None):
    """
    Generate a PDF report of the GPX analysis results.
    Args:
        analyzer: GPXAnalyzer object with analysis results
        km_data: DataFrame with kilometer split data including notes
        total_distance: Total route distance
        pace_minutes: Average pace minutes
        pace_seconds: Average pace seconds
        finish_time: Estimated finish time
        total_elevation_gain: Total elevation gain
        use_metric: Boolean for metric vs imperial units
        route_name: Name of the route for the report title
        create_static_map_image: Function to create the map image (must be provided)
        convert_to_miles: Function to convert km to miles (must be provided)
        convert_to_mph: Function to convert pace (must be provided)
    Returns:
        BytesIO object containing the PDF data
    """
    buffer = BytesIO()
    from reportlab.platypus import PageTemplate, Frame
    from reportlab.lib.enums import TA_CENTER
    def add_page_footer(canvas, doc):
        canvas.saveState()
        footer_text = "Generated by GPX Pace Planner. Created by Brandon Jerome"
        canvas.setFont('Helvetica', 8)
        canvas.setFillGray(0.5)
        text_width = canvas.stringWidth(footer_text, 'Helvetica', 8)
        canvas.drawString((A4[0] - text_width) / 2, 0.5*inch, footer_text)
        canvas.restoreState()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=0.5*inch, rightMargin=0.5*inch, 
                           topMargin=0.75*inch, bottomMargin=1*inch)
    styles = getSampleStyleSheet()
    story = []
    km_data = km_data.copy()
    if 'cutoff_time_formatted' in km_data.columns:
        km_data['cutoff_time_formatted'] = km_data['cutoff_time_formatted'].apply(
            lambda x: '' if (x is pd.NA or pd.isna(x) or x == pd.NaT or 
                           (hasattr(x, '_instance') and str(x) == '<NA>')) else x
        )
    if 'cutoff_buffer_minutes' in km_data.columns:
        km_data['cutoff_buffer_minutes'] = km_data['cutoff_buffer_minutes'].apply(
            lambda x: '' if (x is pd.NA or pd.isna(x) or 
                           (hasattr(x, '_instance') and str(x) == '<NA>')) else x
        )
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=20,
        spaceAfter=30,
        alignment=1
    )
    story.append(Paragraph(f"GPX Pace Analysis Report", title_style))
    story.append(Paragraph(f"Route: {route_name}", styles['Heading2']))
    story.append(Spacer(1, 15))
    try:
        if create_static_map_image is not None:
            map_img_buffer = create_static_map_image(analyzer.final_df, show_arrows=True, width_inches=6, height_inches=3)
            map_img_buffer.seek(0)
            img = Image(map_img_buffer, width=4.5*inch, height=2.25*inch)
            from reportlab.platypus import KeepTogether
            from reportlab.lib.enums import TA_CENTER
            img_table = Table([[img]], colWidths=[4.5*inch])
            img_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            story.append(img_table)
    except Exception:
        story.append(Paragraph(f"Route visualization unavailable", styles['Normal']))
    story.append(Spacer(1, 20))
    date_str = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")
    story.append(Paragraph(f"Generated on: {date_str}", styles['Normal']))
    story.append(Spacer(1, 20))
    story.append(Paragraph("Summary Statistics", styles['Heading2']))
    story.append(Spacer(1, 10))
    if use_metric:
        distance_str = f"{total_distance:.2f} km"
        pace_str = f"{pace_minutes}:{pace_seconds:02d} min/km"
        elevation_str = f"{total_elevation_gain:.0f} m"
    else:
        miles_distance = convert_to_miles(total_distance) if convert_to_miles else total_distance
        elevation_ft = total_elevation_gain * 3.28084
        distance_str = f"{miles_distance:.2f} miles"
        pace_str = f"{pace_minutes}:{pace_seconds:02d} min/mile"
        elevation_str = f"{elevation_ft:.0f} ft"
    summary_data = [
        ['Metric', 'Value'],
        ['Total Distance', distance_str],
        ['Average Pace', pace_str],
        ['Estimated Duration', finish_time],
        ['Elevation Gain', elevation_str]
    ]
    summary_table = Table(summary_data, colWidths=[2*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 20))
    story.append(Paragraph("Pace Splits", styles['Heading2']))
    story.append(Spacer(1, 10))
    has_markers = 'Marker' in km_data.columns
    has_cutoff_time = 'cutoff_time_formatted' in km_data.columns
    has_cutoff_buffer = 'cutoff_buffer_minutes' in km_data.columns
    headers = ['Distance', 'Pace', 'Grade (%)', 'Duration', 'Clock Time']
    if has_cutoff_time:
        headers.append('Cutoff Time')
    if has_cutoff_buffer:
        headers.append('Cutoff Buffer (min)')
    if has_markers:
        headers.append('Marker')
    headers.append('Notes')
    splits_data = [headers]
    for _, row in km_data.iterrows():
        if use_metric:
            distance = f"{row['total_distance']:.2f} km"
        else:
            distance_miles = convert_to_miles(row['total_distance']) if convert_to_miles else row['total_distance']
            distance = f"{distance_miles:.2f} mi"
        if 'pace_display' in row and pd.notna(row['pace_display']) and str(row['pace_display']).strip():
            pace = str(row['pace_display'])
            if use_metric and 'min/km' not in pace:
                pace += ' min/km'
            elif not use_metric and 'min/mi' not in pace:
                pace += ' min/mi'
        else:
            if use_metric:
                pace = f"{row['pace']:.2f} min/km"
            else:
                pace_mph = convert_to_mph(row['pace']) if convert_to_mph else row['pace']
                pace = f"{pace_mph:.2f} min/mi"
        grade = f"{row['grade']:.1f}%"
        time = row['cumulative_time_hms']
        clock_time = row['clock_time']
        notes_text = row.get('Notes', '') if 'Notes' in row else ''
        row_data = [distance, pace, grade, time, clock_time]
        if has_cutoff_time:
            cutoff_time = row.get('cutoff_time_formatted', '') if 'cutoff_time_formatted' in row else ''
            if cutoff_time == pd.NaT or pd.isna(cutoff_time):
                cutoff_time = ''
            row_data.append(cutoff_time)
        if has_cutoff_buffer:
            cutoff_buffer = row.get('cutoff_buffer_minutes', '') if 'cutoff_buffer_minutes' in row else ''
            if pd.notna(cutoff_buffer) and cutoff_buffer != '':
                cutoff_buffer = f"{cutoff_buffer}"
            else:
                cutoff_buffer = ''
            row_data.append(cutoff_buffer)
        if has_markers:
            marker = row.get('Marker', '') if 'Marker' in row else ''
            row_data.append(marker)
        if notes_text and str(notes_text).strip():
            notes_style = ParagraphStyle(
                'NotesStyle',
                parent=styles['Normal'],
                fontSize=7,
                leading=8,
                alignment=0,
                wordWrap='LTR'
            )
            notes = Paragraph(str(notes_text).strip(), notes_style)
        else:
            notes = ''
        row_data.append(notes)
        splits_data.append(row_data)
    col_widths = [1.0*inch, 0.8*inch, 0.6*inch, 0.7*inch, 0.9*inch]
    if has_cutoff_time:
        col_widths.append(0.9*inch)
    if has_cutoff_buffer:
        col_widths.append(1.0*inch)
    if has_markers:
        col_widths.append(0.8*inch)
    col_widths.append(1.3*inch)
    splits_table = Table(splits_data, colWidths=col_widths)
    notes_col_index = len(col_widths) - 1
    splits_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 8),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 1), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
        ('ALIGN', (notes_col_index, 1), (notes_col_index, -1), 'LEFT'),
    ]))
    story.append(splits_table)
    story.append(Spacer(1, 20))
    doc.build(story, onFirstPage=add_page_footer, onLaterPages=add_page_footer)
    buffer.seek(0)
    return buffer
