import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { SplitRow, SummaryStats } from '@/types'
import logoUrl from '@/assets/logo.svg?url'

const KM_TO_MILE = 0.621371
const M_TO_FT = 3.28084

function formatPace(minPerKm: number): string {
  let m = Math.floor(minPerKm)
  let s = Math.round((minPerKm - m) * 60)
  if (s === 60) { m += 1; s = 0 }
  return `${m}:${s.toString().padStart(2, '0')}`
}

function formatPaceImperial(minPerKm: number): string {
  return formatPace(minPerKm / KM_TO_MILE)
}

export interface PdfExportOptions {
  routeName: string
  summary: SummaryStats
  splits: SplitRow[]
  noteMap: Record<number, string>
  useImperial: boolean
  markersOnly: boolean
  elevationChartImg?: string
  paceChartImg?: string
}

async function loadLogoDataUrl(): Promise<string | null> {
  try {
    const img = new Image()
    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve()
      img.onerror = () => reject(new Error('logo load failed'))
      img.src = logoUrl
    })
    const SIZE = 120
    const canvas = document.createElement('canvas')
    canvas.width = SIZE
    canvas.height = SIZE
    const ctx = canvas.getContext('2d')!
    ctx.drawImage(img, 0, 0, SIZE, SIZE)
    return canvas.toDataURL('image/png')
  } catch {
    return null
  }
}

export async function generatePdf(options: PdfExportOptions): Promise<void> {
  const { routeName, summary, splits, noteMap, useImperial, markersOnly } = options

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.width
  const pageHeight = doc.internal.pageSize.height

  const pageFooter = () => {
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text('Generated by Omne Enduro', pageWidth / 2, pageHeight - 5, { align: 'center' })
    doc.setTextColor(0)
  }

  // ── Logo + Title ──────────────────────────────────────────────────────────
  const logoSize = 14 // mm
  const logoDataUrl = await loadLogoDataUrl()
  if (logoDataUrl) {
    doc.addImage(logoDataUrl, 'PNG', 14, 8, logoSize, logoSize)
  }

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('Omne Enduro — Race Plan', pageWidth / 2, 18, { align: 'center' })

  doc.setFontSize(13)
  doc.setFont('helvetica', 'normal')
  doc.text(`Route: ${routeName}`, 14, 28)

  doc.setFontSize(9)
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 35)

  // ── Summary stats ────────────────────────────────────────────────────────
  const distStr = useImperial
    ? `${(summary.total_distance_km * KM_TO_MILE).toFixed(2)} miles`
    : `${summary.total_distance_km.toFixed(2)} km`
  const paceStr = useImperial
    ? `${formatPaceImperial(summary.avg_pace_min_per_km)} min/mile`
    : `${formatPace(summary.avg_pace_min_per_km)} min/km`
  const elevStr = useImperial
    ? `${(summary.elevation_gain_m * M_TO_FT).toFixed(0)} ft`
    : `${summary.elevation_gain_m.toFixed(0)} m`

  autoTable(doc, {
    startY: 42,
    head: [['Metric', 'Value']],
    body: [
      ['Total Distance', distStr],
      ['Average Pace', paceStr],
      ['Estimated Duration', summary.total_duration_hms],
      ['Elevation Gain', elevStr],
    ],
    theme: 'grid',
    headStyles: { fillColor: [80, 80, 80], fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
    margin: { left: 14, right: 14 },
    tableWidth: 100,
    didDrawPage: pageFooter,
  })

  // ── Pace splits ──────────────────────────────────────────────────────────
  const hasCutoffs = splits.some((r) => r.cutoff_time)
  const hasMarkersInPdf = splits.some((r) => r.custom_marker)
  const hasNotesInPdf = Object.values(noteMap).some((n) => n.trim())

  const headers: string[] = [
    useImperial ? 'Dist (mi)' : 'Dist (km)',
    useImperial ? 'Elev (ft)' : 'Elev (m)',
    'Pace',
    'Time',
    'Clock',
  ]
  if (hasCutoffs) { headers.push('Cutoff'); headers.push('Buffer (min)') }
  if (hasMarkersInPdf) headers.push('Marker')
  if (hasNotesInPdf) headers.push('Notes')

  const filteredSplits = markersOnly
    ? splits.filter((row, i) => i === 0 || i === splits.length - 1 || !!row.custom_marker)
    : splits

  const body = filteredSplits.map((row) => {
    const rowDist = useImperial
      ? (row.total_distance_km * KM_TO_MILE).toFixed(2)
      : row.total_distance_km.toFixed(2)
    const rowElev = useImperial
      ? (row.elevation_m * M_TO_FT).toFixed(0)
      : row.elevation_m.toFixed(0)
    const rowPace = useImperial
      ? formatPaceImperial(row.pace_min_per_km)
      : formatPace(row.pace_min_per_km)

    const r: string[] = [rowDist, rowElev, rowPace, row.cumulative_time_hms, row.clock_time ?? '']
    if (hasCutoffs) {
      r.push(row.cutoff_time ?? '')
      const buf = row.cutoff_buffer_min
      r.push(buf != null ? `${buf > 0 ? '+' : ''}${buf.toFixed(0)}` : '')
    }
    if (hasMarkersInPdf) r.push(row.custom_marker ?? '')
    if (hasNotesInPdf) r.push(noteMap[row.km] ?? '')
    return r
  })

  const summaryFinalY = (doc as any).lastAutoTable?.finalY ?? 90
  const notesColIndex = headers.length - 1

  // ── Charts ───────────────────────────────────────────────────────────────
  let chartSectionEndY = summaryFinalY + 8
  const { elevationChartImg, paceChartImg } = options
  if (elevationChartImg || paceChartImg) {
    const margin = 14
    const gap = 4
    const halfW = (pageWidth - margin * 2 - gap) / 2
    const chartH = halfW * (280 / 700)

    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    if (elevationChartImg) {
      doc.text('Elevation Profile', margin, chartSectionEndY)
      doc.addImage(elevationChartImg, 'PNG', margin, chartSectionEndY + 2, halfW, chartH)
    }
    if (paceChartImg) {
      doc.text('Pace Profile', margin + halfW + gap, chartSectionEndY)
      doc.addImage(paceChartImg, 'PNG', margin + halfW + gap, chartSectionEndY + 2, halfW, chartH)
    }
    chartSectionEndY += chartH + 2 + 8
  }
  doc.setFont('helvetica', 'normal')

  // ── Pace splits ──────────────────────────────────────────────────────────
  autoTable(doc, {
    startY: chartSectionEndY,
    head: [headers],
    body,
    theme: 'grid',
    headStyles: { fillColor: [80, 80, 80], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8 },
    margin: { left: 14, right: 14 },
    columnStyles: hasNotesInPdf
      ? { [notesColIndex]: { cellWidth: 38, overflow: 'linebreak' as const } }
      : {},
    didDrawPage: pageFooter,
  })

  const filename = `${routeName.replace(/[^a-z0-9]/gi, '_')}_race_plan.pdf`
  doc.save(filename)
}
